#!/usr/bin/env python3
"""Generate src/animations.rs.

The sprites are procedural and original to this repository. The Clawdmeter
project this one takes its idea from scrapes its artwork from claudepix, which
is copyrighted Anthropic material; nothing from there is used here.

Run:  uv run tools/gen_animations.py

Designing an animation for this panel
-------------------------------------
The panel offers no tearing control (see the module docs in src/co5300.rs), so
the only thing keeping a frame from showing a visible old/new boundary is how
much of the screen it changes. Keep frames close to their neighbours: small
bright shapes on a black background, most of the grid static, and as few cells
as possible differing between consecutive frames.

A "sweep" animation — a contrasty vertical bar travelling horizontally — was
written, measured and removed. It changed up to 40,800 pixels per frame, which
Slint merged into large dirty rectangles costing ~40 ms to render and ~9 ms to
upload against a 55 ms hold. That left almost no headroom for touch, RTC or
PMIC events, and the moving front tore visibly. Reordering the upload did not
fix it; it only changed which artefact you saw.

Pulsing, orbiting and other locally-moving shapes are fine. After adding one,
measure render_us / upload_us / pixels on the physical board, and check it with
your eyes — a screenshot cannot show tearing.
"""

import math
from pathlib import Path

GRID = 20
CELLS = GRID * GRID
CENTER = (GRID - 1) / 2.0

# Index 0 is the background. The ramp follows the UI accent so the splash and
# the dashboard read as one design.
PALETTE = [
    (0x00, 0x00, 0x00),
    (0x0D, 0x25, 0x1E),
    (0x14, 0x3D, 0x32),
    (0x1D, 0x5A, 0x48),
    (0x2F, 0x8F, 0x70),
    (0x45, 0xC3, 0x9A),
    (0x5D, 0xE4, 0xC7),
    (0x8F, 0xF5, 0xDC),
    (0xC9, 0xFF, 0xF2),
    (0xF3, 0xF7, 0xFA),
]


def blank():
    return [0] * CELLS


def put(cells, x, y, value):
    """Write a cell, keeping the brightest value already there."""
    if 0 <= x < GRID and 0 <= y < GRID:
        i = y * GRID + x
        if value > cells[i]:
            cells[i] = value


def disc(cells, cx, cy, radius, inner_shade, edge_shade):
    """Fill a soft-edged disc, shading from the centre outwards."""
    span = int(math.ceil(radius)) + 1
    for y in range(int(cy) - span, int(cy) + span + 1):
        for x in range(int(cx) - span, int(cx) + span + 1):
            d = math.hypot(x - cx, y - cy)
            if d > radius:
                continue
            # 0 at the centre, 1 at the rim.
            t = d / radius if radius > 0 else 0.0
            shade = round(inner_shade + (edge_shade - inner_shade) * t)
            put(cells, x, y, max(1, shade))


def breathe(frame_count=16):
    """A core that swells and settles — the idle mood."""
    frames = []
    for f in range(frame_count):
        phase = f / frame_count
        # Ease in and out so the extremes hold slightly longer.
        swell = (1 - math.cos(2 * math.pi * phase)) / 2
        radius = 4.2 + swell * 3.1
        cells = blank()
        disc(cells, CENTER, CENTER, radius + 1.6, 2, 1)  # halo
        disc(cells, CENTER, CENTER, radius, 9, 4)  # core
        frames.append((cells, 90))
    return frames


def orbit(frame_count=24):
    """A mote circling a steady core — the busy mood."""
    frames = []
    for f in range(frame_count):
        angle = 2 * math.pi * f / frame_count
        cells = blank()
        disc(cells, CENTER, CENTER, 3.4, 7, 3)
        # Trail behind the mote, fading as it recedes.
        for back, shade in ((0, 9), (1, 6), (2, 4), (3, 2)):
            a = angle - back * (2 * math.pi / frame_count)
            mx = CENTER + math.cos(a) * 7.4
            my = CENTER + math.sin(a) * 7.4
            disc(cells, mx, my, 1.6 - back * 0.25, shade, max(1, shade - 3))
        frames.append((cells, 60))
    return frames


ANIMATIONS = [
    ("BREATHE", "breathe", breathe()),
    ("ORBIT", "orbit", orbit()),
]


def render_cells(cells):
    rows = []
    for y in range(GRID):
        row = cells[y * GRID : (y + 1) * GRID]
        rows.append(
            "            " + " ".join(f"{v}," for v in row) + f" // row {y}"
        )
    return "\n".join(rows)


def main():
    out = [
        "//! Sprite data generated by `tools/gen_animations.py` — do not edit by hand.",
        "//!",
        "//! These sprites are procedural and original to this repository.",
        "",
        "use crate::animation::{Animation, Frame};",
        "",
    ]

    palette_rows = ",\n".join(
        f"        [0x{r:02X}, 0x{g:02X}, 0x{b:02X}]" for r, g, b in PALETTE
    )

    for const_name, name, frames in ANIMATIONS:
        out.append(f"static {const_name}_FRAMES: [Frame; {len(frames)}] = [")
        for cells, hold in frames:
            out.append("    Frame {")
            out.append("        cells: [")
            out.append(render_cells(cells))
            out.append("        ],")
            out.append(f"        hold_ms: {hold},")
            out.append("    },")
        out.append("];")
        out.append("")
        out.append(f"pub static {const_name}: Animation = Animation {{")
        out.append(f'    name: "{name}",')
        out.append("    palette: [")
        out.append(palette_rows + ",")
        out.append("    ],")
        out.append(f"    frames: &{const_name}_FRAMES,")
        out.append("};")
        out.append("")

    names = ", ".join(f"&{c}" for c, _, _ in ANIMATIONS)
    out.append("/// Every animation, in the order the UI cycles through them.")
    out.append(f"pub static ANIMATIONS: [&Animation; {len(ANIMATIONS)}] = [{names}];")
    out.append("")

    path = Path(__file__).resolve().parent.parent / "src" / "animations.rs"
    path.write_text("\n".join(out))
    total = sum(len(f) for _, _, f in ANIMATIONS)
    print(f"wrote {path} — {len(ANIMATIONS)} animations, {total} frames")


if __name__ == "__main__":
    main()
